cms/apps/checkout/urls.py
from django.urls import path

from . import views

app_name = 'checkout'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('new/', views.new, name='new'),
    path('summary/', views.summary, name='summary'),
    path('remove/<int:offer_id>', views.remove, name='remove'),
    path('purchase/', views.purchase, name='purchase'),
]

cms/apps/travel/urls.py
from django.urls import path

from . import views

app_name = 'travel'

urlpatterns = [
    path('', views.index, name='index'),
    path('details/<int:travel_id>/', views.details, name='details'),
]

cms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', include('cms.apps.contact.urls')),
    path('newsletter/', include('cms.apps.newsletter.urls')),
    path('', include('cms.apps.authorization.urls')),
    path('travel/', include('cms.apps.travel.urls')),
    path('', include('cms.apps.core.urls')),
    path('checkout/', include('cms.apps.checkout.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

cms/apps/travel/models.py
from django.db import models
from django.db.models import IntegerField
from django.utils import timezone
from django_countries.fields import CountryField


def default_start_date():
    return timezone.now() + timezone.timedelta(days=7)


def default_end_date():
    return timezone.now() + timezone.timedelta(days=14)


class Travel(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    active = models.BooleanField(default=True)
    country = CountryField()
    passengers_limit = IntegerField(default=20)
    start_date = models.DateTimeField(default=default_start_date)
    end_date = models.DateTimeField(default=default_end_date)
    promotion_on_homepage = models.BooleanField(default=False)
    rejections = models.IntegerField(default=0)
    discount_per_person = IntegerField(default=0, verbose_name="Discount per person (%)")
    max_discount = IntegerField(default=0, verbose_name="Max discount per travel (%)")

    def __str__(self):
        return self.title


class TravelImage(models.Model):
    travel = models.ForeignKey(Travel, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField()

cms/apps/travel/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from cms.apps.checkout.models import Purchase
from cms.apps.travel.models import Travel
from django.db.models import Max, Min, Sum


def index(request):
    get = request.GET
    params = get_params(get)
    price_range = {'max': Travel.objects.all().aggregate(Max('price')),
                   'min': Travel.objects.all().aggregate(Min('price'))}
    all_travels = Travel.objects.filter(**params)
    page = get.get('p')
    paginator = Paginator(all_travels, 10)
    travels = paginator.get_page(page)
    return render(request, 'travel/index.html', {'travels': travels, 'params': params, 'price_range': price_range})


def details(request, travel_id):
    travel = get_object_or_404(Travel, pk=travel_id, active=True)
    places_taken = Purchase.objects.filter(travel=travel).aggregate(Sum('passengers'))
    places_left = travel.passengers_limit - (places_taken['passengers__sum'] or 0)
    ref = request.GET.get('ref', None)
    return render(request, 'travel/details.html', {'travel': travel, 'places_left': places_left, 'ref': ref})


def get_params(params):
    result = {'active': True}
    if params.get('name'):
        result['title__contains'] = params.get('name')
    if params.get('country'):
        result['country'] = params.get('country')
    if params.get('price'):
        result['price__range'] = params.getlist('price')

    return result

cms/apps/travel/templates/travel/details.html
{% extends 'base.html' %}
{% load static %}

{% block custom_scripts %}
    <link rel="stylesheet" href="{% static 'gallery.css' %}">
    <script src="{% static 'gallery.js' %}"></script>
{% endblock %}

{% block content %}
    <h2>{{ travel.title }}</h2>

    <div class="row">
        <div class="col-sm-8">
            <div class="travel-details-description p10">
                {{ travel.description }}
            </div>
        </div>
        <div class="col-sm-4">
            <div class="p10">

                <form method="post" action="{% url 'checkout:add' %}">
                    {% csrf_token %}

                    <input type="hidden" name="travel-id" value="{{ travel.id }}">
                    {% if ref %}
                        <input type="hidden" name="ref" value="{{ ref }}">
                    {% endif %}

                    <div class="row">
                        <div class="form-group col-sm-8">
                            Places left: <b>{{ places_left }}</b>
                        </div>
                    </div>

                    {% if travel.discount_per_person %}
                        <div class="row">
                            <div class="form-group col-sm-8">
                                Current discount per person: <b>{{ travel.discount_per_person }}%
                                (Max: {{ travel.max_discount }}%)</b>
                            </div>
                        </div>
                    {% endif %}
                    <div class="row">
                        <div class="form-group col-sm-8">
                            Total price: <b><span id="discount-value"></span></b> PLN
                        </div>
                    </div>

                    <div class="row">

                        <div class="col-lg-12">
                            <label for="count">People:</label>
                            <div class="row">
                                <div class="col-xs-4">
                                    <div class="form-group">
                                        <input name="count" id="count" type="number" class="form-control input-normal"
                                               min="1"
                                               max="{{ places_left }}" value="1">
                                    </div>
                                </div>
                                <div class="col-xs-2">
                                    <div class="form-group">
                                        <button class="btn btn-primary">Buy</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="p10">
        <h4>Price: <b>{{ travel.price }}</b> PLN per one person</h4>
    </div>

    <div class="p10">
        Country: <b>{{ travel.country.name }}</b>
    </div>

    <div class="p10">
        Date: <b>{{ travel.start_date|date:"d F Y" }} - {{ travel.end_date|date:"d F Y" }}</b>
    </div>

    <div class="row">
        {% for image in travel.images.all %}
            <div class="column">
                <img src="{{ image.image.url }}" onclick="openModal();currentSlide({{ forloop.counter }})"
                     class="hover-shadow" style="wh">
            </div>
        {% endfor %}
    </div>

    <div id="myModal" class="modal">
        <span class="close cursor" onclick="closeModal()">&times;</span>
        <div class="modal-content">

            {% for image in travel.images.all %}
                <div class="mySlides">
                    <img src="{{ image.image.url }}" style="width:100%">
                </div>
            {% endfor %}

            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>

            <div class="caption-container">
                <p id="caption"></p>
            </div>

            {% for image in travel.images.all %}
                <div class="column">
                    <img class="demo" src="{{ image.image.url }}" onclick="currentSlide({{ forloop.counter }})">
                </div>
            {% endfor %}

        </div>
    </div>

    <script>
        updateDiscount();

        $("#count").change(function () {
            updateDiscount()
        });

        function updateDiscount() {
            let count = $("#count").val();
            let percentDiscount = count * {{ travel.discount_per_person|default:0 }};

            if (percentDiscount > {{ travel.max_discount|default:0 }}) {
                percentDiscount = {{ travel.max_discount }}
            }

            let price = (count * {{ travel.price }}) * (100 - percentDiscount) / 100;
            $("#discount-value").text(price)
        }
    </script>

{% endblock %}

cms/apps/travel/templates/travel/index.html
{% extends 'base.html' %}
{% load countries %}
{% load static %}

{% block content %}
    <form action="{% url 'travel:index' %}">
        <div class="search-box">
            <div class="container-fluid bg-light ">
                <div class="row align-items-center justify-content-center">
                    <div class="col-md-2 pt-3">
                        <div class="form-group">
                            <label for="name" class="control-label">Name:</label>
                            <input id="name" class="form-control" name="name" title="name" type="text"
                                   placeholder="Name" value="{{ params.title__contains|default:"" }}">
                        </div>
                    </div>
                    <div class="col-md-2 pt-3">
                        <div class="form-group">
                            <label for="country" class="control-label">Country:</label>
                            {% get_countries as countries %}
                            <select id="country" name="country" title="country" class="form-control">
                                <option disabled selected>Country</option>
                                {% for country in countries %}
                                    <option {% ifequal country.code params.country %}selected{% endifequal %}
                                            value="{{ country.code }}">{{ country.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="col-md-2 pt-3">
                        <div class="form-group">
                            <label for="price_min" class="control-label">Price min:</label>
                            <input id="price_min" type="number" class="form-control" name="price" title="price"
                                   value="{{ params.price__range.0|default:price_range.min.price__min }}"
                                   placeholder="Price min">
                        </div>
                    </div>
                    <div class="col-md-2 pt-3">
                        <div class="form-group">
                            <label for="price_max" class="control-label">Price max:</label>
                            <input id="price_max" type="number" class="form-control" name="price" title="price"
                                   value="{{ params.price__range.1|default:price_range.max.price__max }}"
                                   placeholder="Price max">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <label for="" class="control-label">Search</label>
                        <button type="submit" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-search
"></span></button>
                    </div>
                </div>
            </div>
        </div>

        {% if travels %}

            <div class="travels-box">
                {% for travel in travels %}
                    <div class="row">
                        <div class="col-md-6">
                            <a href="{{ travel.images.first.image.url }}">
                                <img class="img-fluid rounded mb-3 mb-md-0 travel-main-image"
                                     src="{{ travel.images.first.image.url }}" alt="">
                            </a>
                        </div>
                        <div class="col-md-6">
                            <h3>{{ travel.title }}</h3>
                            <p>{{ travel.description }}</p>
                            <p><b>Price: </b>{{ travel.price }} PLN</p>
                            <a class="btn btn-primary" href="{% url 'travel:details' travel.id %}">Details</a>
                        </div>
                    </div>
                    <hr>
                {% endfor %}

                <div class="pagination">
            <span class="step-links">
                {% if travels.has_previous %}
                    <button type="submit" value="1" name="p" class="btn">&laquo; first</button>
                    <button type="submit" value="{{ travels.previous_page_number }}" name="p"
                            class="btn">previous</button>
                {% endif %}

                <span class="current">
                    Page {{ travels.number }} of {{ travels.paginator.num_pages }}.
                </span>

                {% if travels.has_next %}
                    <button type="submit" value="{{ travels.next_page_number }}" name="p" class="btn">next</button>
                    <button type="submit" value="{{ travels.paginator.num_pages }}" name="p"
                            class="btn">last &raquo;</button>
                {% endif %}
            </span>
                </div>

            </div>

        {% else %}
            <div class="text-center info-page-icon">
                <img src="{% static 'icons/no-luggage.png' %}" style="width: 20em">
                <div class="p10">
                    <h3>
                        No travels found. Change search criteria or sing up to out newsletter!
                    </h3>
                </div>
            </div>

            <div>Icons made by <a href="https://www.freepik.com/" title="Freepik">Freepik</a> from <a
                    href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a
                    href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC
                3.0
                BY</a></div>
        {% endif %}
    </form>
{% endblock %}