cms/apps/contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.index, name='index'),
    path('save/', views.save, name='save'),
]

cms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', include('cms.apps.contact.urls')),
    path('newsletter/', include('cms.apps.newsletter.urls')),
    path('', include('cms.apps.authorization.urls')),
    path('travel/', include('cms.apps.travel.urls')),
    path('', include('cms.apps.core.urls')),
    path('checkout/', include('cms.apps.checkout.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

cms/apps/contact/models.py
from django.db import models
from django.utils import timezone


class Inquiry(models.Model):
    created_at = models.DateTimeField()
    name = models.CharField(max_length=30)
    email = models.EmailField()
    text = models.TextField(max_length=2000)
    answer = models.TextField(max_length=2000, null=True)
    updated_at = models.DateTimeField(null=True)

    def __str__(self):
        return self.created_at.__format__('%Y-%m-%d %H:%M:%S') + " | " + self.email + " | " + self.text[:100]

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.updated_at = timezone.now()
        super(Inquiry, self).save()

cms/apps/contact/forms.py
from django import forms
from django.forms import ModelForm
from cms.apps.contact.models import Inquiry
from django.forms.widgets import TextInput


class InquiryForm(ModelForm):
    name = forms.CharField(
        widget=TextInput(attrs={'class': 'form-control input-sm chat-input', 'placeholder': 'Name'}))

    email = forms.CharField(
        widget=TextInput(attrs={'class': 'form-control input-sm chat-input', 'placeholder': 'Email'}))

    text = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control input-sm chat-input', 'placeholder': ''}))

    class Meta:
        model = Inquiry
        fields = ['name', 'email', 'text']

cms/apps/contact/views.py
from django.forms import ModelForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone
from django.contrib import messages

from cms.apps.contact.forms import InquiryForm


def index(request):
    form = InquiryForm()
    if request.user.is_authenticated:
        form.fields['name'].initial = request.user.username
        form.fields['email'].initial = request.user.email

    return render(request, 'contact/index.html', {'form': form})


def save(request):
    form = InquiryForm(request.POST)

    if form.is_valid():
        model = form.save(commit=False)  # type: ModelForm
        model.created_at = timezone.now()
        model.save()
        messages.add_message(request, messages.SUCCESS, 'Your message has been sent')

    return HttpResponseRedirect(reverse('contact:index'))

cms/apps/contact/templates/contact/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="text-center">
        <div class="login-form p10">
            <div class="col-md-4 col-md-offset-4">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-success" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="row">
                <div class="col-md-4 col-md-offset-4">

                    <div class="card text-center card  bg-default mb-3">
                        <form action="{% url 'contact:save' %}" method="post">
                            <div class="card-body">
                                {% csrf_token %}
                                {{ form }}
                            </div>
                            <div class="card-footer text-muted p10">
                                <button type="submit" class="btn btn-primary">Send</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}