cms/apps/checkout/urls.py
from django.urls import path

from . import views

app_name = 'checkout'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('new/', views.new, name='new'),
    path('summary/', views.summary, name='summary'),
    path('remove/<int:offer_id>', views.remove, name='remove'),
    path('purchase/', views.purchase, name='purchase'),
]

cms/apps/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
]

cms/apps/travel/urls.py
from django.urls import path

from . import views

app_name = 'travel'

urlpatterns = [
    path('', views.index, name='index'),
    path('details/<int:travel_id>/', views.details, name='details'),
]

cms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', include('cms.apps.contact.urls')),
    path('newsletter/', include('cms.apps.newsletter.urls')),
    path('', include('cms.apps.authorization.urls')),
    path('travel/', include('cms.apps.travel.urls')),
    path('', include('cms.apps.core.urls')),
    path('checkout/', include('cms.apps.checkout.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

cms/apps/checkout/models.py
from django.db import models
from django.contrib.auth import get_user_model

from cms.apps.travel.models import Travel


class Purchase(models.Model):
    travel = models.ForeignKey(Travel, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    customer_first_name = models.CharField(max_length=100)
    customer_last_name = models.CharField(max_length=100)
    customer_address = models.CharField(max_length=100)
    customer_city = models.CharField(max_length=50)
    customer_phone = models.CharField(max_length=15)
    passengers = models.IntegerField()
    passengers_data = models.TextField()

    def __str__(self):
        return self.travel.title + " | " + self.user.username + " | (" + str(self.passengers) + ")"

cms/apps/checkout/views.py
from django.db.models import Sum, F
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
import datetime

from cms.apps.checkout.classes import CheckoutOffer, CheckoutSummary
from cms.apps.checkout.models import Purchase
from cms.apps.checkout.services import process_purchase, send_purchase_mail
from cms.apps.travel.models import Travel


@login_required(login_url='/login/')
def add(request):
    data = request.POST
    count = int(data.get('count') or 1)
    ref = data.get('ref') or None
    offer = CheckoutOffer(data.get('travel-id'), count, ref)
    existing = request.session.get('offers', [])

    for exist in existing:
        if offer.offer_id == exist.offer_id:
            return render(request, 'checkout/offer_exists.html')

    travel = get_object_or_404(Travel, pk=data.get('travel-id'), active=True)
    places_taken = Purchase.objects.filter(travel=travel).aggregate(Sum('passengers'))
    places_left = travel.passengers_limit - (places_taken['passengers__sum'] or 0)

    if count > places_left:
        return render(request, 'checkout/places_taken.html')

    existing.append(offer)
    request.session['offers'] = existing
    return redirect('checkout:new')


@login_required(login_url='/login/')
def new(request):
    return render(request, 'checkout/new.html')


@login_required(login_url='/login/')
def summary(request):
    offers = request.session.get('offers')

    if not offers:
        return redirect('travel:index')

    checkout_summary = CheckoutSummary
    checkout_summary.offers = []

    total = 0
    total_discount = 0

    for checkout_offer in offers:
        count = int(checkout_offer.people)
        offer = Travel.objects.get(pk=checkout_offer.offer_id)

        discount_percent = offer.discount_per_person * count
        if discount_percent > offer.max_discount:
            discount_percent = offer.max_discount

        total += offer.price * count * (100 - discount_percent) / 100
        total_discount += offer.price * count * discount_percent / 100
        checkout_summary.offers.append({'offer': offer, 'people': count, 'total': offer.price * count})

    checkout_summary.total_price = total
    checkout_summary.total_discount = total_discount

    now = datetime.datetime.now()
    years = range(now.year, now.year + 10)
    months = range(1, 12)

    return render(request, 'checkout/summary.html', {'summary': checkout_summary, 'years': years, 'months': months})


@login_required(login_url='/login/')
def remove(request, offer_id):
    existing = request.session.get('offers', [])

    for exist in existing:
        if int(exist.offer_id) == offer_id:
            existing.remove(exist)
            Travel.objects.filter(id=offer_id).update(rejections=F('rejections')+1)

    request.session['offers'] = existing
    return redirect('checkout:summary')


@login_required(login_url='/login/')
def purchase(request):
    data = request.POST
    offers = request.session.get('offers')
    user = request.user

    result = process_purchase(offers, data, user)
    send_purchase_mail(user, offers)

    if result:
        del request.session['offers']
        request.session.modified = True
        return render(request, 'checkout/purchase_completed.html')

    return render(request, 'checkout/error.html')

cms/apps/checkout/templates/checkout/error.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="text-center p10">
        <h2>An unexpected error occurred</h2>

        <div class="info-page-icon">
            <img src="{% static 'icons/overturned-car.png' %}" style="width: 20em">
        </div>

        <div class="info-page-buttons">
            <div class="row">
                <a href="{% url 'core:index' %}">
                    <button class="btn btn-primary">Homepage</button>
                </a>
            </div>
        </div>
    </div>

    <div>Icons made by <a href="https://www.freepik.com/" title="Freepik">Freepik</a> from <a
            href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a
            href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0
        BY</a></div>
{% endblock %}

cms/apps/checkout/templates/checkout/new.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="text-center p10">
        <h2>Travel successfully added!</h2>

        <div class="info-page-icon">
            <img src="{% static 'icons/world.png' %}" style="width: 20em">
        </div>

        <div class="info-page-buttons">
            <div class="row">
                <a href="{% url 'travel:index' %}">
                    <button class="btn btn-secondary">Add something else</button>
                </a>
                <a href="{% url 'checkout:summary' %}">
                    <button class="btn btn-primary">Go to summary</button>
                </a>
            </div>
        </div>
    </div>

    <div>Icons made by <a href="https://www.flaticon.com/authors/prettycons" title="prettycons">prettycons</a> from <a
            href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a
            href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0
        BY</a></div>
{% endblock %}

cms/apps/checkout/templates/checkout/offer_exists.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="text-center p10">
        <h2>Travel already added</h2>

        <div class="info-page-icon">
            <img src="{% static 'icons/search.png' %}" style="width: 20em">
        </div>

        <div class="info-page-buttons">
            <div class="row">
                <a href="{% url 'travel:index' %}">
                    <button class="btn btn-secondary">Add something else</button>
                </a>
                <a href="{% url 'checkout:summary' %}">
                    <button class="btn btn-primary">Go to summary</button>
                </a>
            </div>
        </div>
    </div>

    <div>Icons made by <a href="https://www.flaticon.com/authors/srip" title="srip">srip</a> from <a
            href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a
            href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0
        BY</a></div>
{% endblock %}

cms/apps/checkout/templates/checkout/places_taken.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="text-center p10">
        <h2>Not enough places!</h2>

        <div class="info-page-icon">
            <img src="{% static 'icons/overturned-car.png' %}" style="width: 20em">
        </div>

        <div class="info-page-buttons">
            <div class="row">
                <a href="{% url 'travel:index' %}">
                    <button class="btn btn-primary">Add something else</button>
                </a>
            </div>
        </div>
    </div>

    <div>Icons made by <a href="https://www.freepik.com/" title="Freepik">Freepik</a> from <a
            href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a
            href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0
        BY</a></div>
{% endblock %}

cms/apps/checkout/templates/checkout/purchase_completed.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="text-center p10">
        <h2>Purchase completed!</h2>
        <h6>Pack your luggage</h6>

        <div class="info-page-icon">
            <img src="{% static 'icons/backpack.png' %}" style="width: 20em">
        </div>

        <div class="info-page-buttons">
            <div class="row">
                <a href="{% url 'core:index' %}">
                    <button class="btn btn-primary">Homepage</button>
                </a>
            </div>
        </div>
    </div>

    <div>Icons made by <a href="https://www.flaticon.com/authors/srip" title="srip">srip</a> from <a
            href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a
            href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0
        BY</a></div>
{% endblock %}

cms/apps/checkout/templates/checkout/summary.html
{% extends 'base.html' %}
{% load static %}

{% block custom_scripts %}
    <script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.6/dist/loadingoverlay.min.js"></script>
    <script src="{% static 'checkout.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="checkout-box">
        <div class="row cart-body">
            <form class="form-horizontal" id="checkout-form" method="post" action="{% url 'checkout:purchase' %}">
            {% csrf_token %}
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-md-push-6 col-sm-push-6">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            Review travel
                        </div>
                        <div class="panel-body">
                            {% for offer in summary.offers %}
                                <div class="form-group">
                                    <div class="col-sm-3 col-xs-3">
                                        <img class="img-responsive" src="{{ offer.offer.images.first.image.url }}">
                                    </div>
                                    <div class="col-sm-6 col-xs-6">
                                        <div class="col-xs-12"><b>{{ offer.offer.title }}</b></div>
                                        <div class="col-xs-12">
                                            <small>People: <span>{{ offer.people }}</span></small>
                                        </div>
                                    </div>
                                    <div class="col-sm-3 col-xs-3 text-right">
                                        <h6><span>PLN </span>{{ offer.total }}</h6>
                                    </div>
                                </div>
                                <a href="{% url 'checkout:remove' offer.offer.id %}">Remove</a>
                                <div class="form-group">
                                    <hr>
                                </div>
                            {% endfor %}
                            <div class="form-group">
                                <div class="col-xs-12">
                                    <strong>Discount</strong>
                                    <div class="pull-right"><span>PLN </span><span>{{ summary.total_discount }}</span>
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <strong>Total</strong>
                                    <div class="pull-right"><span>PLN </span><span>{{ summary.total_price }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-info">
                        <div class="panel-heading"><span><i class="glyphicon glyphicon-lock"></i></span> Secure Payment
                        </div>
                        <div class="panel-body">
                            <div class="form-group">
                                <div class="col-md-12"><strong>Credit Card Number:</strong></div>
                                <div class="col-md-12"><input type="text" class="form-control" name="car_number"
                                                              value="" title="card_number" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12"><strong>Card CVV:</strong></div>
                                <div class="col-md-12"><input type="text" class="form-control" name="car_code"
                                                              value="" title="card_cvv" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <strong>Expiration Date</strong>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <select class="form-control" name="" title="card-month" required>
                                        <option value="">Month</option>
                                        {% for month in months %}
                                            <option value="{{ month }}">{{ month }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <select class="form-control" name="card-year" title="card-year" required>
                                        <option value="">Year</option>
                                        {% for year in years %}
                                            <option value="{{ year }}">{{ year }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <button type="button" id="place-order-button" class="btn btn-primary btn-submit-fix pull-right">Place
                                        Order
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-md-pull-6 col-sm-pull-6">
                    <div class="panel panel-info">
                        <div class="panel-heading">Details</div>
                        <div class="panel-body">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <h4>Customer details</h4>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-6 col-xs-12">
                                    <strong>First Name:</strong>
                                    <input type="text" name="first_name" class="form-control" title="first_name" required>
                                </div>
                                <div class="span1"></div>
                                <div class="col-md-6 col-xs-12">
                                    <strong>Last Name:</strong>
                                    <input type="text" name="last_name" class="form-control" title="last_name" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12"><strong>Address:</strong></div>
                                <div class="col-md-12">
                                    <input type="text" name="address" class="form-control" title="address" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12"><strong>City:</strong></div>
                                <div class="col-md-12">
                                    <input type="text" name="city" class="form-control" title="city" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12"><strong>Phone Number:</strong></div>
                                <div class="col-md-12">
                                    <input type="text" name="phone_number" class="form-control" title="phone_number" required>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="panel panel-info">
                        <div class="panel-heading">Passengers data</div>
                        <div class="panel-body">
                            {% for offer in summary.offers %}
                                {% with ''|center:offer.people as range %}
                                    {% for _ in range %}

                                        <h4><b>{{ offer.offer.title }}</b> - Passenger {{ forloop.counter }}: </h4>
                                        <div class="form-group">
                                            <div class="col-md-6 col-xs-12">
                                                First Name:
                                                <input type="text" name="travel.{{ offer.offer.id }}.{{ forloop.counter }}.first_name" class="form-control"
                                                       title="first_name" required>
                                            </div>
                                            <div class="span1"></div>
                                            <div class="col-md-6 col-xs-12">
                                                Last Name:
                                                <input type="text" name="travel.{{ offer.offer.id }}.{{ forloop.counter }}.last_name" class="form-control"
                                                       title="last_name" required>
                                            </div>
                                        </div>
                                        <hr>
                                    {% endfor %}
                                {% endwith %}
                            {% endfor %}
                        </div>
                    </div>
                </div>

            </form>
        </div>
    </div>
{% endblock %}