cms/apps/authorization/urls.py
from django.urls import path

from . import views

app_name = 'authorization'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('login-check/', views.check_login, name='login-check'),
    path('registration/', views.user_registration, name='registration'),
    path('registration-check/', views.check_registration, name='registration-check'),
    path('logout/', views.user_logout, name='logout')
]

cms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', include('cms.apps.contact.urls')),
    path('newsletter/', include('cms.apps.newsletter.urls')),
    path('', include('cms.apps.authorization.urls')),
    path('travel/', include('cms.apps.travel.urls')),
    path('', include('cms.apps.core.urls')),
    path('checkout/', include('cms.apps.checkout.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

cms/apps/authorization/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.forms.widgets import PasswordInput, TextInput


class AuthForm(AuthenticationForm):
    username = forms.CharField(
        widget=TextInput(attrs={'class': 'form-control input-sm chat-input', 'placeholder': 'Username'}))
    password = forms.CharField(
        widget=PasswordInput(attrs={'class': 'form-control input-sm chat-input', 'placeholder': 'Password'}))


class RegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    password1 = forms.CharField(label="Password", strip=False, widget=forms.PasswordInput(
        attrs={'class': 'form-control input-sm chat-input', 'placeholder': 'Password'}))
    password2 = forms.CharField(label="Password confirmation", strip=False, widget=forms.PasswordInput(
        attrs={'class': 'form-control input-sm chat-input', 'placeholder': 'Password confirmation'}))
    field_order = ['username', 'email', 'password1', 'password2']

    class Meta:
        model = get_user_model()
        fields = ("username", "email", "password1", "password2")

cms/apps/authorization/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib import messages

from cms.apps.authorization.forms import AuthForm, RegistrationForm


def user_login(request):
    if request.user.is_authenticated:
        return redirect('core:index')
    form = AuthForm()
    return render(request, 'authorization/login.html', {'form': form})


def check_login(request):
    form = AuthForm(data=request.POST)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')

        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('core:index')

    for message in form.get_invalid_login_error():
        messages.add_message(request, messages.ERROR, message)

    return redirect('authorization:login')


def user_registration(request):
    form = RegistrationForm()
    return render(request, 'authorization/registration.html', {'form': form})


def check_registration(request):
    form = RegistrationForm(request.POST)
    if form.is_valid():
        form.save()
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=raw_password)
        login(request, user)
        return redirect('core:index')

    for message in form.errors.values():
        messages.add_message(request, messages.ERROR, message)

    return redirect('authorization:registration')


def user_logout(request):
    logout(request)
    return redirect('core:index')

cms/apps/authorization/templates/authorization/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="text-center">
        <div class="login-form p10">
            <div class="col-md-4 col-md-offset-4">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="row">
                <div class="col-md-4 col-md-offset-4">

                    <div class="card text-center card  bg-default mb-3">
                        <form action="{% url 'authorization:login-check' %}" method="post">
                            <div class="card-body">
                                {% csrf_token %}
                                {{ form }}
                            </div>
                            <div class="card-footer text-muted p10">
                                <button type="submit" class="btn btn-primary">Login</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div>
            Don't have account? <a href="{% url 'authorization:registration' %}">Registration</a>
        </div>
    </div>
{% endblock %}

cms/apps/authorization/templates/authorization/registration.html
{% extends 'base.html' %}

{% block content %}
    <div class="text-center">
        <div class="login-form p10">
            <div class="col-md-4 col-md-offset-4">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="row">
                <div class="col-md-4 col-md-offset-4">

                    <div class="card text-center card  bg-default mb-3">
                        <form action="{% url 'authorization:registration-check' %}" method="post">
                            <div class="card-body">
                                {% csrf_token %}
                                {{ form }}
                            </div>
                            <div class="card-footer text-muted p10">
                                <button type="submit" class="btn btn-primary">Register</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}